Aag 1591 callback logs
SuperAwesomeLTD/sa-mobile-sdk-android pull request #137
Opened 2022-02-03 11:19 UTC by natashashafqat

Adding debug logs for:
- adLoaded
- adShown
- adClicked
- adEnded
- adClosed

Debug logs can now be seen in Logcat, and can easily be found by keeping a filter on for `Event callback: `.

Video below showing debug logs being registered and easily seen for the above callbacks.

https://user-images.githubusercontent.com/48458132/152332378-b6dee0f5-41da-4c4f-b136-2be1805b9419.mov

2022-02-03 16:13 UTC, gunhansancar requested changes
Please consider my comments for all the changes as I didn't mark them all

2022-02-03 16:13 UTC, gunhansancar commented on superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java
> +                        Log.d("SABannerAd.load.PL_ID", "Event callback: " + eventToSend.toString());
Log tags (the first parameter) should be same for everything, or at least the file based, and it should be short. Please let's use the same tag, it is better for filtering as well.

2022-02-03 16:13 UTC, gunhansancar commented on superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java
> +                        Log.d("SABannerAd.load.ALL_IDs", "Event callback: " + eventToSend.toString());
Same here, I wish we started using the refactored code which contains better logger already

2022-02-03 16:13 UTC, gunhansancar commented on superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SAInterstitialAd.java
> +    @SuppressLint("LongLogTag")
Let's not suppress warnings and solve the issue by using the smaller same tags

2022-02-03 16:15 UTC, natashashafqat commented on superawesome-base/src/main/java/tv/superawesome/sdk/publisher/SABannerAd.java
> +                        Log.d("SABannerAd.load.PL_ID", "Event callback: " + eventToSend.toString());
Makes sense 👍  I wasn't sure on how to label the tags. I can just do file name? So in this case, just `SABannerAd`?

2022-02-04 11:54 UTC, gunhansancar approved these changes

2022-02-04 11:54 UTC, merged